### PR TITLE
Service maintenance

### PR DESCRIPTION
**Pull request by benjay10**
[DL-5672]

Before embarking on more drastic changes to the application, we want to bring all services up to date. This PR aims to achieve that.

**Things worthy of note:**

* Config for the `report-generation-service` was moved to the `/config` mount point due to the use of a newer `mu-javascript-template`
* A new version of the `enrich-submission-service` was made and bumped here to be able to read data from graphs in this application that are different from the ones in Loket

### CODE REVIEW

**Comment by Riadabd** [comment]
* I ran migrations from a fresh slate, and they worked as expected. ✅
* I noticed the `report-generation` service was crashing; I changed an entry inside the service's `volumes` section as OP have done it [here](https://github.com/lblod/app-organization-portal/blob/development/docker-compose.yml#L286).

Can you also try it on your side and see if you get the crashing issue and if changing the volume mount fixes it?

**Comment by Riadabd** [comment]
I tried the producer/consumer flow between `app-digitaal-loket` and this app:
* It correctly consumes the needed data, and all data is present in the database (no broken links or faulty data based on my local checks).
* The submission shows up in the DatabankErediensten frontend table with all the data filled in.
* However, clicking `Bekijk` on the DatabankErediensten frontend displays a blank page. After looking into it, it seems the cause is the `enrich-submission` service.

The snippet causing the issue is this:
* `v1.4.0`: https://github.com/lblod/enrich-submission-service/blob/v1.4.0/lib/submission-document.js#L310-L324
* `v1.5.1` and above: https://github.com/lblod/enrich-submission-service/blob/v1.4.0/lib/submission-document.js#L310-L324

`reqState.submissionGraph` in `v1.5.1` and above yields the wrong graph in DatabankErediensten, which leads to a blank page when trying to view a submission's details.

**Comment by benjay10** [comment]
> * I ran migrations from a fresh slate, and they worked as expected. ✅
> 
>     * I noticed the `report-generation` service was crashing; I changed an entry inside the service's `volumes` section as the organisatie-portaal team has done it [here](https://github.com/lblod/app-organization-portal/blob/development/docker-compose.yml#L286).
> 
> 
> Can you also try it on your side and see if you get the crashing issue and if changing the volume mount fixes it?

Good catch, as per usual! The service changed to a more modern JavaScript template, which uses this new mount point for external config.

**Comment by benjay10** [comment]
> I tried the producer/consumer flow between `app-digitaal-loket` and this app:
> 
>     * It correctly consumes the needed data, and all data is present in the database (no broken links or faulty data based on my local checks).
> 
>     * The submission shows up in the DatabankErediensten frontend table with all the data filled in.
> 
>     * However, clicking `Bekijk` on the DatabankErediensten frontend displays a blank page. After looking into it, it seems the cause is the `enrich-submission` service.
> 
> 
> The snippet causing the issue is this:
> 
>     * `v1.4.0`: https://github.com/lblod/enrich-submission-service/blob/v1.4.0/lib/submission-document.js#L310-L324
> 
>     * `v1.5.1` and above: https://github.com/lblod/enrich-submission-service/blob/v1.4.0/lib/submission-document.js#L310-L324
> 
> 
> `reqState.submissionGraph` in `v1.5.1` and above yields the wrong graph in DatabankErediensten, which leads to a blank page when trying to view a submission's details.

Because I also saw a blank screen before I made any changes to the stack, I assumed it was broken because I did not have the needed files on my local set-up. That was true, but not the only problem. After changing the `enrich-submission-service` and adding the files locally, it works now (apart for some errors on loading the remote-data URLs, but that is an issue in the data). See https://github.com/lblod/enrich-submission-service/pull/17

**Review by Riadabd — APPROVED** [review]
Tested the `report-generation-service` config path and `enrich-submission` version bump changes, and all works as expected!

I also looked at organizations that can access another's documents (e.g., `CKB Boom` can see submissions from `Kerkfabriek Hart van Boom`), and they also show up there and open up as expected.

**Pull request merged**
